import type { Metadata } from "next";
import { Livvic, Inter, Noto_Serif } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const notoSerifHeading = Noto_Serif({subsets:['latin'],variable:'--font-heading'});

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const livvic = Livvic({
  variable: "--font-livvic",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Channel",
  icons: [{ url: "/logo.svg", type: "image/svg+xml" }, { url: "/favicon.ico" }],
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", livvic.variable, "font-sans", inter.variable, notoSerifHeading.variable)}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
